name: gpu-cellpose-coolix
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python==3.11.*
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - qtpy
    - numpy>=1.26.0
    - numba>=0.58.0
    - scipy
    - torch>=2.1
    - opencv-python-headless
    - pyqtgraph>=0.11.0rc0
    - natsort
    - GitPython
    - tqdm
    - tifffile
    - fastremap
    - scikit-image>=0.22.0
    - scikit-learn>=1.3.2
    - scipy>=1.11.3
    - cellpose
    - roifile
    
  
